version: '3'

services:
    db:
      image: postgres
      container_name: pickabudatabase
      ports:
        - 5432:5432
      environment:
       - POSTGRES_USER=${POSTGRES_USER}
       - POSTGRES_DB=${POSTGRES_DB}
       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      volumes:
       - ./seeds.sql:/docker-entrypoint-initdb.d/seeds.sql
      restart: always
      command: ["postgres", "-c", "log_statement=all"]
    pickabu:
      build: .
      container_name: pickabuapi
      ports:
       - 3000:3000
      environment:
        - POSTGRES_HOST=db
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      links:
        - db

